// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQkOpiJsPido_m46sR_DJhD151S-Wsz0g',
    appId: '1:542890294201:web:567e78a89345137a7a1468',
    messagingSenderId: '542890294201',
    projectId: 'proyecto1fb-f392b',
    authDomain: 'proyecto1fb-f392b.firebaseapp.com',
    storageBucket: 'proyecto1fb-f392b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5btf9Tq5yAss-6ZzCkaBtMN-OrRhQYl8',
    appId: '1:542890294201:android:efa90e8433a186387a1468',
    messagingSenderId: '542890294201',
    projectId: 'proyecto1fb-f392b',
    storageBucket: 'proyecto1fb-f392b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIV-qpq8JF8HVHWNJXmh0UcY0onfbihkk',
    appId: '1:542890294201:ios:55fb2ed3df961fcd7a1468',
    messagingSenderId: '542890294201',
    projectId: 'proyecto1fb-f392b',
    storageBucket: 'proyecto1fb-f392b.appspot.com',
    iosClientId: '542890294201-70sn43chu94vap0ht965qhlam7so55m1.apps.googleusercontent.com',
    iosBundleId: 'com.example.userView',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIV-qpq8JF8HVHWNJXmh0UcY0onfbihkk',
    appId: '1:542890294201:ios:55fb2ed3df961fcd7a1468',
    messagingSenderId: '542890294201',
    projectId: 'proyecto1fb-f392b',
    storageBucket: 'proyecto1fb-f392b.appspot.com',
    iosClientId: '542890294201-70sn43chu94vap0ht965qhlam7so55m1.apps.googleusercontent.com',
    iosBundleId: 'com.example.userView',
  );
}
